# Generated by Django 3.2.4 on 2021-07-11 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PRODUCT', '0002_auto_20210711_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_add', models.CharField(default='Full address', max_length=1000)),
                ('town', models.CharField(max_length=50)),
                ('landmark', models.CharField(default='name', max_length=300)),
                ('pin', models.CharField(default=71, max_length=8)),
                ('ph_no', models.CharField(default=91, max_length=11)),
                ('alt_ph_no', models.CharField(blank=True, default=91, max_length=11, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('order_price', models.FloatField(blank=True, default=1, null=True)),
                ('order_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('is_placed', models.BooleanField(default=False)),
                ('placed', models.CharField(choices=[('PLACED', 'PLACED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('CANCEL', 'CANCEL')], default='PLACED', max_length=20)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('o_palced_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.products')),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.address')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_quantity', models.PositiveIntegerField(default=1)),
                ('toal_payable_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cart_total', models.IntegerField(default=1)),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_p', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.products')),
            ],
        ),
    ]
