# Generated by Django 3.2.4 on 2021-07-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0004_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='alt_ph_no',
        ),
        migrations.RemoveField(
            model_name='address',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='address',
            name='town',
        ),
    ]
