# Generated by Django 3.2.4 on 2021-07-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0005_auto_20210712_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='placed',
        ),
        migrations.AddField(
            model_name='order',
            name='tip_coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.tip'),
        ),
    ]
